// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package subscriptions

import (
	"github.com/colinfike/yougo-premium/internal/config"
)

// Injectors from wire.go:

func InitializeSubManager() *SubManager {
	configConfig := config.NewConfig()
	subManager := NewSubManager(configConfig)
	return subManager
}
