// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package subscriptions

import (
	"github.com/colinfike/yougo-premium/internal/config"
)

// Injectors from wire.go:

func InitializeSubManager() (*SubManager, error) {
	configConfig := config.NewConfig()
	subManager, err := NewSubManager(configConfig)
	if err != nil {
		return nil, err
	}
	return subManager, nil
}
