// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package video

import (
	"github.com/colinfike/yougo-premium/internal/config"
)

// Injectors from wire.go:

func InitializeDownloader() (*Downloader, error) {
	configConfig := config.NewConfig()
	downloader, err := NewDownloader(configConfig)
	if err != nil {
		return nil, err
	}
	return downloader, nil
}
