// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package youtube

import (
	"github.com/colinfike/yougo-premium/internal/config"
)

// Injectors from wire.go:

func InitializeYoutubeManager() (*YoutubeManager, error) {
	configConfig := config.NewConfig()
	youtubeManager, err := NewYoutubeManager(configConfig)
	if err != nil {
		return nil, err
	}
	return youtubeManager, nil
}
