// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package youtube

import (
	"github.com/colinfike/yougo-premium/internal/config"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeWrapper() (*Wrapper, error) {
	configConfig := config.NewConfig()
	youtubeYoutubeClient, err := NewYoutubeClient(configConfig)
	if err != nil {
		return nil, err
	}
	wrapper, err := NewWrapper(youtubeYoutubeClient)
	if err != nil {
		return nil, err
	}
	return wrapper, nil
}

func InitializeYoutubeClient() (*youtubeClient, error) {
	configConfig := config.NewConfig()
	youtubeYoutubeClient, err := NewYoutubeClient(configConfig)
	if err != nil {
		return nil, err
	}
	return youtubeYoutubeClient, nil
}

// wire.go:

var NewYoutubeClientSet = wire.NewSet(
	NewYoutubeClient, wire.Bind(new(client), new(*youtubeClient)))
